---
apiVersion: kubefledged.k8s.io/v1alpha1
kind: ImageCache
metadata:
  # Name of the image cache. A cluster can have multiple image cache objects
  name: imagecache1
  # The kubernetes namespace to be used for this image cache. You can choose a different namepace as per your preference
  namespace: default
spec:
  # The "cacheSpec" field allows a user to define a list of images and onto which worker nodes those images should be cached (i.e. pre-pulled).
  cacheSpec:
  # Specifies a list of images (nginx and tomcat:10.0.0) with no node selector, hence these images will be cached in all the nodes in the cluster
  {{- range .Values.images }}
  - images:
    {{- range .images }}
    - {{ . | quote }}
    {{- end }}
    {{- if .nodeSelector }}
    nodeSelector:
      {{- toYaml .nodeSelector | nindent 6 }}
    {{- end }}
  {{- end}}
