apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubefledged.fullname" . }}-webhook-server
  namespace: {{ include "kubefledged.namespace" . }}
  labels:
    {{- include "kubefledged.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubefledged.selectorLabels" . | nindent 6 }}-webhook-server
  template:
    metadata:
      labels:
        {{- include "kubefledged.selectorLabels" . | nindent 8 }}-webhook-server
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kubefledged.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.kubefledgedWebhookServerRepository }}:{{ .Chart.AppVersion }}
          command: {{ .Values.command.kubefledgedWebhookServerCommand }}
          args:
            - "--stderrthreshold={{ .Values.args.webhookServerLogLevel }}"
            - "--cert-file={{ if .Values.certManager.enabled }}/cert/tls.crt{{ else }}{{ .Values.args.webhookServerCertFile }}{{ end }}"
            - "--key-file={{ if .Values.certManager.enabled }}/cert/tls.key{{ else }}{{ .Values.args.webhookServerKeyFile }}{{ end }}"
            - "--port={{ .Values.args.webhookServerPort }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KUBEFLEDGED_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: tls-secret
            mountPath: {{if .Values.certManager.enabled }}"/cert"{{else}}"/var/run/secrets/webhook-server"{{end}}
            readOnly: true
      volumes:
      - name: tls-secret
        secret:
          {{- if .Values.certManager.enabled }}
          secretName: {{ template "kubefledged.fullname" . }}-admission
          {{- else }}
          secretName: "kubefledged-webhook-server"
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
